### ISSUE TITLE
`String` <-> `Cursor` and `byte[]` <-> `Cursor`

### ISSUE THREAD

**Issue by alexjg** [automerge/automerge-java#13]
Cursors are primarily useful when you store them elsewhere and look them up, to support this we need to expose serialization to strings to be interoperable with javascript and bytes for places where interop is not important.

**Comment by eneroth** [comment]
Cursors is the cat's pajamas

**Comment by eneroth** [comment]
When do you think this might land in a release? While most of the other stuff I can work around (or it turns out it was actually "shit behind the wheel" a.k.a my fault), I'm a bit stalled due to the missing cursor bits in the Java API.

I must also emphasize that this is not a demand of any sort, I understand the dynamics of open source work, and that you probably have a lot on your plate. And a huge _thank you_ for the attention you given this already.

**Comment by alexjg** [comment]
It'll be this week. I'm just finishing up a big ole patch to the rust library to make it `no_std`, which means that we can remove the glibc dynamic linking on linux. Once I've got that merged then I'll implement this stuff and release a new java library.
